name: deployment_pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  install_dependencies_and_check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install root dependencies
        run: npm install
      - name: Install frontend dependencies
        run: npm --prefix frontend install
      - name: Check style
        run: npm run eslint
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install backend dependencies
        run: npm install
      - name: run backend tests
        env:
          NODE_ENV: test
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: 3003
        run: npm test
  playwright_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install backend dependencies
        run: npm install
      - name: Install frontend dependencies
        run: npm --prefix frontend install
      - name: build frontend
        run: npm run build:frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: run playwright tests
        env:
          NODE_ENV: test
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: 3003
        run: npm run test:e2e
  deploy:
    needs:
      - install_dependencies_and_check_style
      - backend_tests
      - playwright_tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
